name: health_tracker
description: A professional health tracker app
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  charts_flutter: ^0.12.0
  speech_to_text: ^6.1.1
  text_to_speech: ^0.2.3
  image_picker: ^0.8.6
  sqflite: ^2.2.6
  path_provider: ^2.0.11
  intl: ^0.17.0
  provider: ^6.0.4
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true